server:
  httpPort: 88
authentication:
  mode: SystemAssignedManagedIdentity
telemetry:
  applicationInsights:
    instrumentationKey: ABC
    isEnabled: false
  containerLogs:
    isEnabled: true
  defaultVerbosity: information