server:
  httpPort: 88
  authentication: managedIdentity
telemetry:
  applicationInsights:
    instrumentationKey: ABC
    isEnabled: false
  containerLogs:
    isEnabled: true
  defaultVerbosity: information