server:
  httpPort: 88
  authentication: managedIdentity
telemetry:
  applicationInsights:
    instrumentationKey: ABC
    isEnabled: true
    verbosity: warning
  containerLogs:
    isEnabled: true
    verbosity: trace
  defaultVerbosity: trace